### ISSUE TITLE
Developer Blog AJAX call broken since September

### ISSUE THREAD

**Issue by mattandrews** [guardian/developers-site#78]
Hi folks! The feed of developer blog posts for the dev site shows the most recent post as being from September 2015 (the [API call](http://content.guardianapis.com/search?tag=info/developer-blog&page-size=3&show-fields=trailText&api-key=85nszu4nbfdzh2zrakh74k2w) confirms this). This is wrong though – see https://www.theguardian.com/info/developer-blog – maybe the query needs updating?!

**Comment by rrees** [comment]
@cb372 just wants to make sure the developer blog reflects his glory at Scala World indefinitely... Any ideas why the new content isn't being indexed Chris?

**Comment by mchv** [comment]
Hi @mattandrews. Just looked into it and this is because the more recent articles have their rights all set to false preventing them to be shared.

**Comment by mattandrews** [comment]
Ahh, that's weird. Presume that's not intentional...?

**Comment by mchv** [comment]
@mattandrews no, we are investigating now

**Comment by mchv** [comment]
@mattandrews several emails later and fix related to migration to `https`, this is now fixed!

**Comment by mattandrews** [comment]
Great job! Thanks :)
